/***************************************************************************
 *   Copyright (C) 2010 by Erik Sohns   *
 *   erik.sohns@web.de   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_SOUND_EVENT_H
#define RPG_SOUND_EVENT_H

enum RPG_Sound_Event
{
  EVENT_MAIN_TITLE = 0,
  EVENT_HIT,
  EVENT_MISS,
  //
  RPG_SOUND_EVENT_MAX,
  RPG_SOUND_EVENT_INVALID
};

#include <ace/Global_Macros.h>

#include <map>
#include <string>

typedef std::map<RPG_Sound_Event, std::string> RPG_Sound_EventToStringTable_t;
typedef RPG_Sound_EventToStringTable_t::const_iterator RPG_Sound_EventToStringTableIterator_t;

class RPG_Sound_EventHelper
{
 public:
  inline static void init()
  {
    myRPG_Sound_EventToStringTable.clear();
    myRPG_Sound_EventToStringTable.insert(std::make_pair(EVENT_MAIN_TITLE, ACE_TEXT_ALWAYS_CHAR("EVENT_MAIN_TITLE")));
    myRPG_Sound_EventToStringTable.insert(std::make_pair(EVENT_HIT, ACE_TEXT_ALWAYS_CHAR("EVENT_HIT")));
    myRPG_Sound_EventToStringTable.insert(std::make_pair(EVENT_MISS, ACE_TEXT_ALWAYS_CHAR("EVENT_MISS")));
  };

  inline static std::string RPG_Sound_EventToString(const RPG_Sound_Event& element_in)
  {
    std::string result;
    RPG_Sound_EventToStringTableIterator_t iterator = myRPG_Sound_EventToStringTable.find(element_in);
    if (iterator != myRPG_Sound_EventToStringTable.end())
      result = iterator->second;
    else
      result = ACE_TEXT_ALWAYS_CHAR("RPG_SOUND_EVENT_INVALID");

    return result;
  };

  inline static RPG_Sound_Event stringToRPG_Sound_Event(const std::string& string_in)
  {
    RPG_Sound_EventToStringTableIterator_t iterator = myRPG_Sound_EventToStringTable.begin();
    do
    {
      if (iterator->second == string_in)
        return iterator->first;

      iterator++;
    } while (iterator != myRPG_Sound_EventToStringTable.end());

    return RPG_SOUND_EVENT_INVALID;
  };

  static RPG_Sound_EventToStringTable_t myRPG_Sound_EventToStringTable;

 private:
  ACE_UNIMPLEMENTED_FUNC(RPG_Sound_EventHelper());
  ACE_UNIMPLEMENTED_FUNC(RPG_Sound_EventHelper(const RPG_Sound_EventHelper&));
  ACE_UNIMPLEMENTED_FUNC(RPG_Sound_EventHelper& operator=(const RPG_Sound_EventHelper&));
};

#endif
