
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_CLIENT_INCL_H
#define RPG_CLIENT_INCL_H

#include <vector>
#include "rpg_client_graphicsmode.h"
#include "rpg_client_runtimestate.h"

#endif
