/***************************************************************************
 *   Copyright (C) 2010 by Erik Sohns   *
 *   erik.sohns@web.de   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_GRAPHICS_STYLEUNION_H
#define RPG_GRAPHICS_STYLEUNION_H

struct RPG_Graphics_StyleUnion
{
  union
  {
    RPG_Graphics_FloorStyle floorstyle;
    RPG_Graphics_StairsStyle stairsstyle;
    RPG_Graphics_WallStyle wallstyle;
    RPG_Graphics_EdgeStyle edgestyle;
    RPG_Graphics_DoorStyle doorstyle;
  };

  enum Discriminator_t
  {
    FLOORSTYLE,
    STAIRSSTYLE,
    WALLSTYLE,
    EDGESTYLE,
    DOORSTYLE,
    INVALID
  };
  Discriminator_t discriminator;
};

#endif
