
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_GRAPHICS_GRAPHICTYPEUNION_H
#define RPG_GRAPHICS_GRAPHICTYPEUNION_H

#include "rpg_graphics_exports.h"

struct RPG_Graphics_Export RPG_Graphics_GraphicTypeUnion
{
  union
  {
    RPG_Graphics_Cursor cursor;
    RPG_Graphics_Font font;
    RPG_Graphics_Image image;
    RPG_Graphics_Sprite sprite;
    RPG_Graphics_TileGraphic tilegraphic;
    RPG_Graphics_TileSetGraphic tilesetgraphic;
  };

  enum Discriminator_t
  {
    CURSOR,
    FONT,
    IMAGE,
    SPRITE,
    TILEGRAPHIC,
    TILESETGRAPHIC,
    INVALID
  };
  Discriminator_t discriminator;
};

#endif
