/***************************************************************************
 *   Copyright (C) 2010 by Erik Sohns   *
 *   erik.sohns@web.de   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_GRAPHICS_FONT_H
#define RPG_GRAPHICS_FONT_H

enum RPG_Graphics_Font
{
  FONT_MAIN_SMALL = 0,
  FONT_MAIN_NORMAL,
  FONT_MAIN_LARGE,
  //
  RPG_GRAPHICS_FONT_MAX,
  RPG_GRAPHICS_FONT_INVALID
};

#include <ace/Global_Macros.h>

#include <map>
#include <string>

typedef std::map<RPG_Graphics_Font, std::string> RPG_Graphics_FontToStringTable_t;
typedef RPG_Graphics_FontToStringTable_t::const_iterator RPG_Graphics_FontToStringTableIterator_t;

class RPG_Graphics_FontHelper
{
 public:
  inline static void init()
  {
    myRPG_Graphics_FontToStringTable.clear();
    myRPG_Graphics_FontToStringTable.insert(std::make_pair(FONT_MAIN_SMALL, ACE_TEXT_ALWAYS_CHAR("FONT_MAIN_SMALL")));
    myRPG_Graphics_FontToStringTable.insert(std::make_pair(FONT_MAIN_NORMAL, ACE_TEXT_ALWAYS_CHAR("FONT_MAIN_NORMAL")));
    myRPG_Graphics_FontToStringTable.insert(std::make_pair(FONT_MAIN_LARGE, ACE_TEXT_ALWAYS_CHAR("FONT_MAIN_LARGE")));
  };

  inline static std::string RPG_Graphics_FontToString(const RPG_Graphics_Font& element_in)
  {
    std::string result;
    RPG_Graphics_FontToStringTableIterator_t iterator = myRPG_Graphics_FontToStringTable.find(element_in);
    if (iterator != myRPG_Graphics_FontToStringTable.end())
      result = iterator->second;
    else
      result = ACE_TEXT_ALWAYS_CHAR("RPG_GRAPHICS_FONT_INVALID");

    return result;
  };

  inline static RPG_Graphics_Font stringToRPG_Graphics_Font(const std::string& string_in)
  {
    RPG_Graphics_FontToStringTableIterator_t iterator = myRPG_Graphics_FontToStringTable.begin();
    do
    {
      if (iterator->second == string_in)
        return iterator->first;

      iterator++;
    } while (iterator != myRPG_Graphics_FontToStringTable.end());

    return RPG_GRAPHICS_FONT_INVALID;
  };

  static RPG_Graphics_FontToStringTable_t myRPG_Graphics_FontToStringTable;

 private:
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_FontHelper());
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_FontHelper(const RPG_Graphics_FontHelper&));
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_FontHelper& operator=(const RPG_Graphics_FontHelper&));
};

#endif
