/***************************************************************************
 *   Copyright (C) 2010 by Erik Sohns   *
 *   erik.sohns@web.de   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_GRAPHICS_INTERFACEELEMENTTYPE_H
#define RPG_GRAPHICS_INTERFACEELEMENTTYPE_H

enum RPG_Graphics_InterfaceElementType
{
  INTERFACEELEMENT_CORNER_TL = 0,
  INTERFACEELEMENT_CORNER_TR,
  INTERFACEELEMENT_CORNER_BL,
  INTERFACEELEMENT_CORNER_BR,
  INTERFACEELEMENT_BORDER_TOP,
  INTERFACEELEMENT_BORDER_RIGHT,
  INTERFACEELEMENT_BORDER_LEFT,
  INTERFACEELEMENT_BORDER_BOTTOM,
  INTERFACEELEMENT_BORDER_CENTER,
  //
  RPG_GRAPHICS_INTERFACEELEMENTTYPE_MAX,
  RPG_GRAPHICS_INTERFACEELEMENTTYPE_INVALID
};

#include <ace/Global_Macros.h>

#include <map>
#include <string>

typedef std::map<RPG_Graphics_InterfaceElementType, std::string> RPG_Graphics_InterfaceElementTypeToStringTable_t;
typedef RPG_Graphics_InterfaceElementTypeToStringTable_t::const_iterator RPG_Graphics_InterfaceElementTypeToStringTableIterator_t;

class RPG_Graphics_InterfaceElementTypeHelper
{
 public:
  inline static void init()
  {
    myRPG_Graphics_InterfaceElementTypeToStringTable.clear();
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_CORNER_TL, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_CORNER_TL")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_CORNER_TR, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_CORNER_TR")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_CORNER_BL, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_CORNER_BL")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_CORNER_BR, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_CORNER_BR")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_BORDER_TOP, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_BORDER_TOP")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_BORDER_RIGHT, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_BORDER_RIGHT")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_BORDER_LEFT, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_BORDER_LEFT")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_BORDER_BOTTOM, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_BORDER_BOTTOM")));
    myRPG_Graphics_InterfaceElementTypeToStringTable.insert(std::make_pair(INTERFACEELEMENT_BORDER_CENTER, ACE_TEXT_ALWAYS_CHAR("INTERFACEELEMENT_BORDER_CENTER")));
  };

  inline static std::string RPG_Graphics_InterfaceElementTypeToString(const RPG_Graphics_InterfaceElementType& element_in)
  {
    std::string result;
    RPG_Graphics_InterfaceElementTypeToStringTableIterator_t iterator = myRPG_Graphics_InterfaceElementTypeToStringTable.find(element_in);
    if (iterator != myRPG_Graphics_InterfaceElementTypeToStringTable.end())
      result = iterator->second;
    else
      result = ACE_TEXT_ALWAYS_CHAR("RPG_GRAPHICS_INTERFACEELEMENTTYPE_INVALID");

    return result;
  };

  inline static RPG_Graphics_InterfaceElementType stringToRPG_Graphics_InterfaceElementType(const std::string& string_in)
  {
    RPG_Graphics_InterfaceElementTypeToStringTableIterator_t iterator = myRPG_Graphics_InterfaceElementTypeToStringTable.begin();
    do
    {
      if (iterator->second == string_in)
        return iterator->first;

      iterator++;
    } while (iterator != myRPG_Graphics_InterfaceElementTypeToStringTable.end());

    return RPG_GRAPHICS_INTERFACEELEMENTTYPE_INVALID;
  };

  static RPG_Graphics_InterfaceElementTypeToStringTable_t myRPG_Graphics_InterfaceElementTypeToStringTable;

 private:
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_InterfaceElementTypeHelper());
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_InterfaceElementTypeHelper(const RPG_Graphics_InterfaceElementTypeHelper&));
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_InterfaceElementTypeHelper& operator=(const RPG_Graphics_InterfaceElementTypeHelper&));
};

#endif
