
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_GRAPHICS_FONT_H
#define RPG_GRAPHICS_FONT_H

enum RPG_Graphics_Font
{
  FONT_MAIN_SMALL = 0,
  FONT_MAIN_NORMAL,
  FONT_MAIN_LARGE,
  //
  RPG_GRAPHICS_FONT_MAX,
  RPG_GRAPHICS_FONT_INVALID
};

#include "ace/Global_Macros.h"

#include <map>
#include <string>

typedef std::map<RPG_Graphics_Font, std::string> RPG_Graphics_FontToStringTable_t;
typedef RPG_Graphics_FontToStringTable_t::const_iterator RPG_Graphics_FontToStringTableIterator_t;

class RPG_Graphics_FontHelper
{
 public:
  inline static void init()
  {
    myRPG_Graphics_FontToStringTable.clear();
    myRPG_Graphics_FontToStringTable.insert(std::make_pair(FONT_MAIN_SMALL, ACE_TEXT_ALWAYS_CHAR("FONT_MAIN_SMALL")));
    myRPG_Graphics_FontToStringTable.insert(std::make_pair(FONT_MAIN_NORMAL, ACE_TEXT_ALWAYS_CHAR("FONT_MAIN_NORMAL")));
    myRPG_Graphics_FontToStringTable.insert(std::make_pair(FONT_MAIN_LARGE, ACE_TEXT_ALWAYS_CHAR("FONT_MAIN_LARGE")));
  };

  inline static std::string RPG_Graphics_FontToString(const RPG_Graphics_Font& element_in)
  {
    std::string result;
    RPG_Graphics_FontToStringTableIterator_t iterator = myRPG_Graphics_FontToStringTable.find(element_in);
    if (iterator != myRPG_Graphics_FontToStringTable.end())
      result = iterator->second;
    else
      result = ACE_TEXT_ALWAYS_CHAR("RPG_GRAPHICS_FONT_INVALID");

    return result;
  };

  inline static RPG_Graphics_Font stringToRPG_Graphics_Font(const std::string& string_in)
  {
    RPG_Graphics_FontToStringTableIterator_t iterator = myRPG_Graphics_FontToStringTable.begin();
    do
    {
      if (iterator->second == string_in)
        return iterator->first;

      iterator++;
    } while (iterator != myRPG_Graphics_FontToStringTable.end());

    return RPG_GRAPHICS_FONT_INVALID;
  };

  static RPG_Graphics_FontToStringTable_t myRPG_Graphics_FontToStringTable;

 private:
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_FontHelper());
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_FontHelper(const RPG_Graphics_FontHelper&));
  ACE_UNIMPLEMENTED_FUNC(RPG_Graphics_FontHelper& operator=(const RPG_Graphics_FontHelper&));
};

#endif
