
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_COMBAT_INCL_H
#define RPG_COMBAT_INCL_H

#include <vector>
#include "rpg_combat_attackform.h"
#include "rpg_combat_rangedeffectunion.h"
#include "rpg_combat_rangedattackproperties.h"
#include "rpg_combat_attacksituation.h"
#include "rpg_combat_defensesituation.h"
#include "rpg_combat_specialattack.h"
#include "rpg_combat_specialdamagetype.h"
#include "rpg_combat_damagetypeunion.h"
#include "rpg_combat_damageduration.h"
#include "rpg_combat_checktypeunion.h"
#include "rpg_combat_check.h"
#include "rpg_combat_damagereductiontype.h"
#include "rpg_combat_damagecountermeasure.h"
#include "rpg_combat_otherdamagetype.h"
#include "rpg_combat_otherdamage.h"
#include "rpg_combat_damageelement.h"
#include "rpg_combat_damage.h"

#endif
