
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_COMBAT_DAMAGE_H
#define RPG_COMBAT_DAMAGE_H

struct RPG_Combat_Damage
{
  std::vector<RPG_Combat_DamageElement> elements;
  bool elementsAreInclusive;
};

#endif
