
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_COMBAT_OTHERDAMAGE_H
#define RPG_COMBAT_OTHERDAMAGE_H

struct RPG_Combat_OtherDamage
{
  RPG_Combat_OtherDamageType type;
  signed char modifier;
  std::vector<RPG_Combat_DamageCounterMeasure> counterMeasures;
};

#endif
