
// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_COMBAT_DAMAGEDURATION_H
#define RPG_COMBAT_DAMAGEDURATION_H

struct RPG_Combat_DamageDuration
{
  RPG_Dice_Roll incubationPeriod;
  RPG_Dice_Roll totalPeriod;
  unsigned short int interval;
  unsigned short int totalDuration;
  bool vicinity;
};

#endif
