// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "rpg_engine_XML_tree.h"

// RPG_Engine_Command_XMLTree_Type
// 

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (value v)
: ::xml_schema::string (_xsd_RPG_Engine_Command_XMLTree_Type_literals_[v])
{
}

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const char* v)
: ::xml_schema::string (v)
{
}

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const ::std::string& v)
: ::xml_schema::string (v)
{
}

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const ::xml_schema::string& v)
: ::xml_schema::string (v)
{
}

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const RPG_Engine_Command_XMLTree_Type& v,
                                 ::xml_schema::flags f,
                                 ::xml_schema::container* c)
: ::xml_schema::string (v, f, c)
{
}

RPG_Engine_Command_XMLTree_Type& RPG_Engine_Command_XMLTree_Type::
operator= (value v)
{
  static_cast< ::xml_schema::string& > (*this) = 
  ::xml_schema::string (_xsd_RPG_Engine_Command_XMLTree_Type_literals_[v]);

  return *this;
}


// RPG_Engine_EntityMode_XMLTree_Type
// 

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (value v)
: ::xml_schema::string (_xsd_RPG_Engine_EntityMode_XMLTree_Type_literals_[v])
{
}

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const char* v)
: ::xml_schema::string (v)
{
}

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const ::std::string& v)
: ::xml_schema::string (v)
{
}

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const ::xml_schema::string& v)
: ::xml_schema::string (v)
{
}

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const RPG_Engine_EntityMode_XMLTree_Type& v,
                                    ::xml_schema::flags f,
                                    ::xml_schema::container* c)
: ::xml_schema::string (v, f, c)
{
}

RPG_Engine_EntityMode_XMLTree_Type& RPG_Engine_EntityMode_XMLTree_Type::
operator= (value v)
{
  static_cast< ::xml_schema::string& > (*this) = 
  ::xml_schema::string (_xsd_RPG_Engine_EntityMode_XMLTree_Type_literals_[v]);

  return *this;
}


// RPG_Engine_Player_XMLTree_Type
// 

const RPG_Engine_Player_XMLTree_Type::position_type& RPG_Engine_Player_XMLTree_Type::
position () const
{
  return this->position_.get ();
}

RPG_Engine_Player_XMLTree_Type::position_type& RPG_Engine_Player_XMLTree_Type::
position ()
{
  return this->position_.get ();
}

void RPG_Engine_Player_XMLTree_Type::
position (const position_type& x)
{
  this->position_.set (x);
}

void RPG_Engine_Player_XMLTree_Type::
position (::std::auto_ptr< position_type > x)
{
  this->position_.set (x);
}

const RPG_Engine_Player_XMLTree_Type::mode_sequence& RPG_Engine_Player_XMLTree_Type::
mode () const
{
  return this->mode_;
}

RPG_Engine_Player_XMLTree_Type::mode_sequence& RPG_Engine_Player_XMLTree_Type::
mode ()
{
  return this->mode_;
}

void RPG_Engine_Player_XMLTree_Type::
mode (const mode_sequence& s)
{
  this->mode_ = s;
}

const RPG_Engine_Player_XMLTree_Type::sprite_type& RPG_Engine_Player_XMLTree_Type::
sprite () const
{
  return this->sprite_.get ();
}

RPG_Engine_Player_XMLTree_Type::sprite_type& RPG_Engine_Player_XMLTree_Type::
sprite ()
{
  return this->sprite_.get ();
}

void RPG_Engine_Player_XMLTree_Type::
sprite (const sprite_type& x)
{
  this->sprite_.set (x);
}

void RPG_Engine_Player_XMLTree_Type::
sprite (::std::auto_ptr< sprite_type > x)
{
  this->sprite_.set (x);
}


// RPG_Engine_Level_XMLTree_Type
// 

const RPG_Engine_Level_XMLTree_Type::name_type& RPG_Engine_Level_XMLTree_Type::
name () const
{
  return this->name_.get ();
}

RPG_Engine_Level_XMLTree_Type::name_type& RPG_Engine_Level_XMLTree_Type::
name ()
{
  return this->name_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
name (const name_type& x)
{
  this->name_.set (x);
}

void RPG_Engine_Level_XMLTree_Type::
name (::std::auto_ptr< name_type > x)
{
  this->name_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::environment_type& RPG_Engine_Level_XMLTree_Type::
environment () const
{
  return this->environment_.get ();
}

RPG_Engine_Level_XMLTree_Type::environment_type& RPG_Engine_Level_XMLTree_Type::
environment ()
{
  return this->environment_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
environment (const environment_type& x)
{
  this->environment_.set (x);
}

void RPG_Engine_Level_XMLTree_Type::
environment (::std::auto_ptr< environment_type > x)
{
  this->environment_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::monster_sequence& RPG_Engine_Level_XMLTree_Type::
monster () const
{
  return this->monster_;
}

RPG_Engine_Level_XMLTree_Type::monster_sequence& RPG_Engine_Level_XMLTree_Type::
monster ()
{
  return this->monster_;
}

void RPG_Engine_Level_XMLTree_Type::
monster (const monster_sequence& s)
{
  this->monster_ = s;
}

const RPG_Engine_Level_XMLTree_Type::spawn_interval_type& RPG_Engine_Level_XMLTree_Type::
spawn_interval () const
{
  return this->spawn_interval_.get ();
}

RPG_Engine_Level_XMLTree_Type::spawn_interval_type& RPG_Engine_Level_XMLTree_Type::
spawn_interval ()
{
  return this->spawn_interval_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
spawn_interval (const spawn_interval_type& x)
{
  this->spawn_interval_.set (x);
}

void RPG_Engine_Level_XMLTree_Type::
spawn_interval (::std::auto_ptr< spawn_interval_type > x)
{
  this->spawn_interval_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::spawn_probability_type& RPG_Engine_Level_XMLTree_Type::
spawn_probability () const
{
  return this->spawn_probability_.get ();
}

RPG_Engine_Level_XMLTree_Type::spawn_probability_type& RPG_Engine_Level_XMLTree_Type::
spawn_probability ()
{
  return this->spawn_probability_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
spawn_probability (const spawn_probability_type& x)
{
  this->spawn_probability_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::max_spawned_type& RPG_Engine_Level_XMLTree_Type::
max_spawned () const
{
  return this->max_spawned_.get ();
}

RPG_Engine_Level_XMLTree_Type::max_spawned_type& RPG_Engine_Level_XMLTree_Type::
max_spawned ()
{
  return this->max_spawned_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
max_spawned (const max_spawned_type& x)
{
  this->max_spawned_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::amble_probability_type& RPG_Engine_Level_XMLTree_Type::
amble_probability () const
{
  return this->amble_probability_.get ();
}

RPG_Engine_Level_XMLTree_Type::amble_probability_type& RPG_Engine_Level_XMLTree_Type::
amble_probability ()
{
  return this->amble_probability_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
amble_probability (const amble_probability_type& x)
{
  this->amble_probability_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::map_type& RPG_Engine_Level_XMLTree_Type::
map () const
{
  return this->map_.get ();
}

RPG_Engine_Level_XMLTree_Type::map_type& RPG_Engine_Level_XMLTree_Type::
map ()
{
  return this->map_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
map (const map_type& x)
{
  this->map_.set (x);
}

void RPG_Engine_Level_XMLTree_Type::
map (::std::auto_ptr< map_type > x)
{
  this->map_.set (x);
}

const RPG_Engine_Level_XMLTree_Type::door_sequence& RPG_Engine_Level_XMLTree_Type::
door () const
{
  return this->door_;
}

RPG_Engine_Level_XMLTree_Type::door_sequence& RPG_Engine_Level_XMLTree_Type::
door ()
{
  return this->door_;
}

void RPG_Engine_Level_XMLTree_Type::
door (const door_sequence& s)
{
  this->door_ = s;
}

const RPG_Engine_Level_XMLTree_Type::style_type& RPG_Engine_Level_XMLTree_Type::
style () const
{
  return this->style_.get ();
}

RPG_Engine_Level_XMLTree_Type::style_type& RPG_Engine_Level_XMLTree_Type::
style ()
{
  return this->style_.get ();
}

void RPG_Engine_Level_XMLTree_Type::
style (const style_type& x)
{
  this->style_.set (x);
}

void RPG_Engine_Level_XMLTree_Type::
style (::std::auto_ptr< style_type > x)
{
  this->style_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// RPG_Engine_Command_XMLTree_Type
//

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const ::xercesc::DOMElement& e,
                                 ::xml_schema::flags f,
                                 ::xml_schema::container* c)
: ::xml_schema::string (e, f, c)
{
  _xsd_RPG_Engine_Command_XMLTree_Type_convert ();
}

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const ::xercesc::DOMAttr& a,
                                 ::xml_schema::flags f,
                                 ::xml_schema::container* c)
: ::xml_schema::string (a, f, c)
{
  _xsd_RPG_Engine_Command_XMLTree_Type_convert ();
}

RPG_Engine_Command_XMLTree_Type::
RPG_Engine_Command_XMLTree_Type (const ::std::string& s,
                                 const ::xercesc::DOMElement* e,
                                 ::xml_schema::flags f,
                                 ::xml_schema::container* c)
: ::xml_schema::string (s, e, f, c)
{
  _xsd_RPG_Engine_Command_XMLTree_Type_convert ();
}

RPG_Engine_Command_XMLTree_Type* RPG_Engine_Command_XMLTree_Type::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class RPG_Engine_Command_XMLTree_Type (*this, f, c);
}

RPG_Engine_Command_XMLTree_Type::value RPG_Engine_Command_XMLTree_Type::
_xsd_RPG_Engine_Command_XMLTree_Type_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_RPG_Engine_Command_XMLTree_Type_literals_);
  const value* i (::std::lower_bound (
                    _xsd_RPG_Engine_Command_XMLTree_Type_indexes_,
                    _xsd_RPG_Engine_Command_XMLTree_Type_indexes_ + 22,
                    *this,
                    c));

  if (i == _xsd_RPG_Engine_Command_XMLTree_Type_indexes_ + 22 || _xsd_RPG_Engine_Command_XMLTree_Type_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const RPG_Engine_Command_XMLTree_Type::
_xsd_RPG_Engine_Command_XMLTree_Type_literals_[22] =
{
  "COMMAND_ATTACK",
  "COMMAND_ATTACK_FULL",
  "COMMAND_ATTACK_STANDARD",
  "COMMAND_DOOR_CLOSE",
  "COMMAND_DOOR_OPEN",
  "COMMAND_IDLE",
  "COMMAND_RUN",
  "COMMAND_SEARCH",
  "COMMAND_STEP",
  "COMMAND_STOP",
  "COMMAND_TRAVEL",
  "COMMAND_E2C_ENTITY_ADD",
  "COMMAND_E2C_ENTITY_REMOVE",
  "COMMAND_E2C_ENTITY_HIT",
  "COMMAND_E2C_ENTITY_MISS",
  "COMMAND_E2C_ENTITY_CONDITION",
  "COMMAND_E2C_ENTITY_POSITION",
  "COMMAND_E2C_ENTITY_VISION",
  "COMMAND_E2C_ENTITY_LEVEL_UP",
  "COMMAND_E2C_INIT",
  "COMMAND_E2C_MESSAGE",
  "COMMAND_E2C_QUIT"
};

const RPG_Engine_Command_XMLTree_Type::value RPG_Engine_Command_XMLTree_Type::
_xsd_RPG_Engine_Command_XMLTree_Type_indexes_[22] =
{
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_ATTACK,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_ATTACK_FULL,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_ATTACK_STANDARD,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_DOOR_CLOSE,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_DOOR_OPEN,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_ADD,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_CONDITION,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_HIT,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_LEVEL_UP,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_MISS,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_POSITION,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_REMOVE,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_ENTITY_VISION,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_INIT,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_MESSAGE,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_E2C_QUIT,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_IDLE,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_RUN,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_SEARCH,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_STEP,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_STOP,
  ::RPG_Engine_Command_XMLTree_Type::COMMAND_TRAVEL
};

// RPG_Engine_EntityMode_XMLTree_Type
//

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const ::xercesc::DOMElement& e,
                                    ::xml_schema::flags f,
                                    ::xml_schema::container* c)
: ::xml_schema::string (e, f, c)
{
  _xsd_RPG_Engine_EntityMode_XMLTree_Type_convert ();
}

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const ::xercesc::DOMAttr& a,
                                    ::xml_schema::flags f,
                                    ::xml_schema::container* c)
: ::xml_schema::string (a, f, c)
{
  _xsd_RPG_Engine_EntityMode_XMLTree_Type_convert ();
}

RPG_Engine_EntityMode_XMLTree_Type::
RPG_Engine_EntityMode_XMLTree_Type (const ::std::string& s,
                                    const ::xercesc::DOMElement* e,
                                    ::xml_schema::flags f,
                                    ::xml_schema::container* c)
: ::xml_schema::string (s, e, f, c)
{
  _xsd_RPG_Engine_EntityMode_XMLTree_Type_convert ();
}

RPG_Engine_EntityMode_XMLTree_Type* RPG_Engine_EntityMode_XMLTree_Type::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class RPG_Engine_EntityMode_XMLTree_Type (*this, f, c);
}

RPG_Engine_EntityMode_XMLTree_Type::value RPG_Engine_EntityMode_XMLTree_Type::
_xsd_RPG_Engine_EntityMode_XMLTree_Type_convert () const
{
  ::xsd::cxx::tree::enum_comparator< char > c (_xsd_RPG_Engine_EntityMode_XMLTree_Type_literals_);
  const value* i (::std::lower_bound (
                    _xsd_RPG_Engine_EntityMode_XMLTree_Type_indexes_,
                    _xsd_RPG_Engine_EntityMode_XMLTree_Type_indexes_ + 4,
                    *this,
                    c));

  if (i == _xsd_RPG_Engine_EntityMode_XMLTree_Type_indexes_ + 4 || _xsd_RPG_Engine_EntityMode_XMLTree_Type_literals_[*i] != *this)
  {
    throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
  }

  return *i;
}

const char* const RPG_Engine_EntityMode_XMLTree_Type::
_xsd_RPG_Engine_EntityMode_XMLTree_Type_literals_[4] =
{
  "ENTITYMODE_FIGHTING",
  "ENTITYMODE_RUNNING",
  "ENTITYMODE_SEARCHING",
  "ENTITYMODE_TRAVELLING"
};

const RPG_Engine_EntityMode_XMLTree_Type::value RPG_Engine_EntityMode_XMLTree_Type::
_xsd_RPG_Engine_EntityMode_XMLTree_Type_indexes_[4] =
{
  ::RPG_Engine_EntityMode_XMLTree_Type::ENTITYMODE_FIGHTING,
  ::RPG_Engine_EntityMode_XMLTree_Type::ENTITYMODE_RUNNING,
  ::RPG_Engine_EntityMode_XMLTree_Type::ENTITYMODE_SEARCHING,
  ::RPG_Engine_EntityMode_XMLTree_Type::ENTITYMODE_TRAVELLING
};

// RPG_Engine_Player_XMLTree_Type
//

RPG_Engine_Player_XMLTree_Type::
RPG_Engine_Player_XMLTree_Type (const name_type& name,
                                const alignment_type& alignment,
                                const attributes_type& attributes,
                                const defaultSize_type& defaultSize,
                                const maxHP_type& maxHP,
                                const conditions_type& conditions,
                                const HP_type& HP,
                                const XP_type& XP,
                                const gold_type& gold,
                                const inventory_type& inventory,
                                const gender_type& gender,
                                const classXML_type& classXML,
                                const offhand_type& offhand,
                                const position_type& position,
                                const sprite_type& sprite)
: ::RPG_Player_PlayerXML_XMLTree_Type (name,
                                       alignment,
                                       attributes,
                                       defaultSize,
                                       maxHP,
                                       conditions,
                                       HP,
                                       XP,
                                       gold,
                                       inventory,
                                       gender,
                                       classXML,
                                       offhand),
  position_ (position, ::xml_schema::flags (), this),
  mode_ (::xml_schema::flags (), this),
  sprite_ (sprite, ::xml_schema::flags (), this)
{
}

RPG_Engine_Player_XMLTree_Type::
RPG_Engine_Player_XMLTree_Type (const name_type& name,
                                ::std::auto_ptr< alignment_type >& alignment,
                                ::std::auto_ptr< attributes_type >& attributes,
                                const defaultSize_type& defaultSize,
                                const maxHP_type& maxHP,
                                ::std::auto_ptr< conditions_type >& conditions,
                                const HP_type& HP,
                                const XP_type& XP,
                                const gold_type& gold,
                                ::std::auto_ptr< inventory_type >& inventory,
                                const gender_type& gender,
                                ::std::auto_ptr< classXML_type >& classXML,
                                const offhand_type& offhand,
                                ::std::auto_ptr< position_type >& position,
                                const sprite_type& sprite)
: ::RPG_Player_PlayerXML_XMLTree_Type (name,
                                       alignment,
                                       attributes,
                                       defaultSize,
                                       maxHP,
                                       conditions,
                                       HP,
                                       XP,
                                       gold,
                                       inventory,
                                       gender,
                                       classXML,
                                       offhand),
  position_ (position, ::xml_schema::flags (), this),
  mode_ (::xml_schema::flags (), this),
  sprite_ (sprite, ::xml_schema::flags (), this)
{
}

RPG_Engine_Player_XMLTree_Type::
RPG_Engine_Player_XMLTree_Type (const RPG_Engine_Player_XMLTree_Type& x,
                                ::xml_schema::flags f,
                                ::xml_schema::container* c)
: ::RPG_Player_PlayerXML_XMLTree_Type (x, f, c),
  position_ (x.position_, f, this),
  mode_ (x.mode_, f, this),
  sprite_ (x.sprite_, f, this)
{
}

RPG_Engine_Player_XMLTree_Type::
RPG_Engine_Player_XMLTree_Type (const ::xercesc::DOMElement& e,
                                ::xml_schema::flags f,
                                ::xml_schema::container* c)
: ::RPG_Player_PlayerXML_XMLTree_Type (e, f | ::xml_schema::flags::base, c),
  position_ (f, this),
  mode_ (f, this),
  sprite_ (f, this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
    this->parse (p, f);
  }
}

void RPG_Engine_Player_XMLTree_Type::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  this->::RPG_Player_PlayerXML_XMLTree_Type::parse (p, f);

  for (; p.more_elements (); p.next_element ())
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // position
    //
    if (n.name () == "position" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< position_type > r (
        position_traits::create (i, f, this));

      if (!position_.present ())
      {
        this->position_.set (r);
        continue;
      }
    }

    // mode
    //
    if (n.name () == "mode" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< mode_type > r (
        mode_traits::create (i, f, this));

      this->mode_.push_back (r);
      continue;
    }

    // sprite
    //
    if (n.name () == "sprite" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< sprite_type > r (
        sprite_traits::create (i, f, this));

      if (!sprite_.present ())
      {
        this->sprite_.set (r);
        continue;
      }
    }

    break;
  }

  if (!position_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "position",
      "urn:rpg");
  }

  if (!sprite_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "sprite",
      "urn:rpg");
  }
}

RPG_Engine_Player_XMLTree_Type* RPG_Engine_Player_XMLTree_Type::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class RPG_Engine_Player_XMLTree_Type (*this, f, c);
}

RPG_Engine_Player_XMLTree_Type::
~RPG_Engine_Player_XMLTree_Type ()
{
}

bool
operator== (const RPG_Engine_Player_XMLTree_Type& x, const RPG_Engine_Player_XMLTree_Type& y)
{
  if (!(static_cast< const ::RPG_Player_PlayerXML_XMLTree_Type& > (x) ==
        static_cast< const ::RPG_Player_PlayerXML_XMLTree_Type& > (y)))
    return false;

  if (!(x.position () == y.position ()))
    return false;

  if (!(x.mode () == y.mode ()))
    return false;

  if (!(x.sprite () == y.sprite ()))
    return false;

  return true;
}

bool
operator!= (const RPG_Engine_Player_XMLTree_Type& x, const RPG_Engine_Player_XMLTree_Type& y)
{
  return !(x == y);
}

// RPG_Engine_Level_XMLTree_Type
//

RPG_Engine_Level_XMLTree_Type::
RPG_Engine_Level_XMLTree_Type (const name_type& name,
                               const environment_type& environment,
                               const spawn_interval_type& spawn_interval,
                               const spawn_probability_type& spawn_probability,
                               const max_spawned_type& max_spawned,
                               const amble_probability_type& amble_probability,
                               const map_type& map,
                               const style_type& style)
: ::xml_schema::type (),
  name_ (name, ::xml_schema::flags (), this),
  environment_ (environment, ::xml_schema::flags (), this),
  monster_ (::xml_schema::flags (), this),
  spawn_interval_ (spawn_interval, ::xml_schema::flags (), this),
  spawn_probability_ (spawn_probability, ::xml_schema::flags (), this),
  max_spawned_ (max_spawned, ::xml_schema::flags (), this),
  amble_probability_ (amble_probability, ::xml_schema::flags (), this),
  map_ (map, ::xml_schema::flags (), this),
  door_ (::xml_schema::flags (), this),
  style_ (style, ::xml_schema::flags (), this)
{
}

RPG_Engine_Level_XMLTree_Type::
RPG_Engine_Level_XMLTree_Type (const name_type& name,
                               ::std::auto_ptr< environment_type >& environment,
                               ::std::auto_ptr< spawn_interval_type >& spawn_interval,
                               const spawn_probability_type& spawn_probability,
                               const max_spawned_type& max_spawned,
                               const amble_probability_type& amble_probability,
                               const map_type& map,
                               ::std::auto_ptr< style_type >& style)
: ::xml_schema::type (),
  name_ (name, ::xml_schema::flags (), this),
  environment_ (environment, ::xml_schema::flags (), this),
  monster_ (::xml_schema::flags (), this),
  spawn_interval_ (spawn_interval, ::xml_schema::flags (), this),
  spawn_probability_ (spawn_probability, ::xml_schema::flags (), this),
  max_spawned_ (max_spawned, ::xml_schema::flags (), this),
  amble_probability_ (amble_probability, ::xml_schema::flags (), this),
  map_ (map, ::xml_schema::flags (), this),
  door_ (::xml_schema::flags (), this),
  style_ (style, ::xml_schema::flags (), this)
{
}

RPG_Engine_Level_XMLTree_Type::
RPG_Engine_Level_XMLTree_Type (const RPG_Engine_Level_XMLTree_Type& x,
                               ::xml_schema::flags f,
                               ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_ (x.name_, f, this),
  environment_ (x.environment_, f, this),
  monster_ (x.monster_, f, this),
  spawn_interval_ (x.spawn_interval_, f, this),
  spawn_probability_ (x.spawn_probability_, f, this),
  max_spawned_ (x.max_spawned_, f, this),
  amble_probability_ (x.amble_probability_, f, this),
  map_ (x.map_, f, this),
  door_ (x.door_, f, this),
  style_ (x.style_, f, this)
{
}

RPG_Engine_Level_XMLTree_Type::
RPG_Engine_Level_XMLTree_Type (const ::xercesc::DOMElement& e,
                               ::xml_schema::flags f,
                               ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_ (f, this),
  environment_ (f, this),
  monster_ (f, this),
  spawn_interval_ (f, this),
  spawn_probability_ (f, this),
  max_spawned_ (f, this),
  amble_probability_ (f, this),
  map_ (f, this),
  door_ (f, this),
  style_ (f, this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
    this->parse (p, f);
  }
}

void RPG_Engine_Level_XMLTree_Type::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_elements (); p.next_element ())
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name
    //
    if (n.name () == "name" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< name_type > r (
        name_traits::create (i, f, this));

      if (!name_.present ())
      {
        this->name_.set (r);
        continue;
      }
    }

    // environment
    //
    if (n.name () == "environment" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< environment_type > r (
        environment_traits::create (i, f, this));

      if (!environment_.present ())
      {
        this->environment_.set (r);
        continue;
      }
    }

    // monster
    //
    if (n.name () == "monster" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< monster_type > r (
        monster_traits::create (i, f, this));

      this->monster_.push_back (r);
      continue;
    }

    // spawn_interval
    //
    if (n.name () == "spawn_interval" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< spawn_interval_type > r (
        spawn_interval_traits::create (i, f, this));

      if (!spawn_interval_.present ())
      {
        this->spawn_interval_.set (r);
        continue;
      }
    }

    // spawn_probability
    //
    if (n.name () == "spawn_probability" && n.namespace_ () == "urn:rpg")
    {
      if (!spawn_probability_.present ())
      {
        this->spawn_probability_.set (spawn_probability_traits::create (i, f, this));
        continue;
      }
    }

    // max_spawned
    //
    if (n.name () == "max_spawned" && n.namespace_ () == "urn:rpg")
    {
      if (!max_spawned_.present ())
      {
        this->max_spawned_.set (max_spawned_traits::create (i, f, this));
        continue;
      }
    }

    // amble_probability
    //
    if (n.name () == "amble_probability" && n.namespace_ () == "urn:rpg")
    {
      if (!amble_probability_.present ())
      {
        this->amble_probability_.set (amble_probability_traits::create (i, f, this));
        continue;
      }
    }

    // map
    //
    if (n.name () == "map" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< map_type > r (
        map_traits::create (i, f, this));

      if (!map_.present ())
      {
        this->map_.set (r);
        continue;
      }
    }

    // door
    //
    if (n.name () == "door" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< door_type > r (
        door_traits::create (i, f, this));

      this->door_.push_back (r);
      continue;
    }

    // style
    //
    if (n.name () == "style" && n.namespace_ () == "urn:rpg")
    {
      ::std::auto_ptr< style_type > r (
        style_traits::create (i, f, this));

      if (!style_.present ())
      {
        this->style_.set (r);
        continue;
      }
    }

    break;
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "name",
      "urn:rpg");
  }

  if (!environment_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "environment",
      "urn:rpg");
  }

  if (!spawn_interval_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "spawn_interval",
      "urn:rpg");
  }

  if (!spawn_probability_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "spawn_probability",
      "urn:rpg");
  }

  if (!max_spawned_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "max_spawned",
      "urn:rpg");
  }

  if (!amble_probability_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "amble_probability",
      "urn:rpg");
  }

  if (!map_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "map",
      "urn:rpg");
  }

  if (!style_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "style",
      "urn:rpg");
  }
}

RPG_Engine_Level_XMLTree_Type* RPG_Engine_Level_XMLTree_Type::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class RPG_Engine_Level_XMLTree_Type (*this, f, c);
}

RPG_Engine_Level_XMLTree_Type::
~RPG_Engine_Level_XMLTree_Type ()
{
}

bool
operator== (const RPG_Engine_Level_XMLTree_Type& x, const RPG_Engine_Level_XMLTree_Type& y)
{
  if (!(x.name () == y.name ()))
    return false;

  if (!(x.environment () == y.environment ()))
    return false;

  if (!(x.monster () == y.monster ()))
    return false;

  if (!(x.spawn_interval () == y.spawn_interval ()))
    return false;

  if (!(x.spawn_probability () == y.spawn_probability ()))
    return false;

  if (!(x.max_spawned () == y.max_spawned ()))
    return false;

  if (!(x.amble_probability () == y.amble_probability ()))
    return false;

  if (!(x.map () == y.map ()))
    return false;

  if (!(x.door () == y.door ()))
    return false;

  if (!(x.style () == y.style ()))
    return false;

  return true;
}

bool
operator!= (const RPG_Engine_Level_XMLTree_Type& x, const RPG_Engine_Level_XMLTree_Type& y)
{
  return !(x == y);
}

#include <ostream>

::std::ostream&
operator<< (::std::ostream& o, RPG_Engine_Command_XMLTree_Type::value i)
{
  return o << RPG_Engine_Command_XMLTree_Type::_xsd_RPG_Engine_Command_XMLTree_Type_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const RPG_Engine_Command_XMLTree_Type& i)
{
  return o << static_cast< const ::xml_schema::string& > (i);
}

::std::ostream&
operator<< (::std::ostream& o, RPG_Engine_EntityMode_XMLTree_Type::value i)
{
  return o << RPG_Engine_EntityMode_XMLTree_Type::_xsd_RPG_Engine_EntityMode_XMLTree_Type_literals_[i];
}

::std::ostream&
operator<< (::std::ostream& o, const RPG_Engine_EntityMode_XMLTree_Type& i)
{
  return o << static_cast< const ::xml_schema::string& > (i);
}

::std::ostream&
operator<< (::std::ostream& o, const RPG_Engine_Player_XMLTree_Type& i)
{
  o << static_cast< const ::RPG_Player_PlayerXML_XMLTree_Type& > (i);

  o << ::std::endl << "position: " << i.position ();
  for (RPG_Engine_Player_XMLTree_Type::mode_const_iterator
       b (i.mode ().begin ()), e (i.mode ().end ());
       b != e; ++b)
  {
    o << ::std::endl << "mode: " << *b;
  }

  o << ::std::endl << "sprite: " << i.sprite ();
  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const RPG_Engine_Level_XMLTree_Type& i)
{
  o << ::std::endl << "name: " << i.name ();
  o << ::std::endl << "environment: " << i.environment ();
  for (RPG_Engine_Level_XMLTree_Type::monster_const_iterator
       b (i.monster ().begin ()), e (i.monster ().end ());
       b != e; ++b)
  {
    o << ::std::endl << "monster: " << *b;
  }

  o << ::std::endl << "spawn_interval: " << i.spawn_interval ();
  o << ::std::endl << "spawn_probability: " << i.spawn_probability ();
  o << ::std::endl << "max_spawned: " << i.max_spawned ();
  o << ::std::endl << "amble_probability: " << i.amble_probability ();
  o << ::std::endl << "map: " << i.map ();
  for (RPG_Engine_Level_XMLTree_Type::door_const_iterator
       b (i.door ().begin ()), e (i.door ().end ());
       b != e; ++b)
  {
    o << ::std::endl << "door: " << *b;
  }

  o << ::std::endl << "style: " << i.style ();
  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (const ::std::string& u,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
    ::engine_player_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (const ::std::string& u,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
    ::engine_player_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
    ::engine_player_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::std::istream& is,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::engine_player_t (isrc, f, p);
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::std::istream& is,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::engine_player_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::engine_player_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::engine_player_t (isrc, f, p);
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::engine_player_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::engine_player_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::xercesc::InputSource& i,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
    ::engine_player_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::xercesc::InputSource& i,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
    ::engine_player_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
    ::engine_player_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (const ::xercesc::DOMDocument& d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

    ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
      ::engine_player_t (
        c, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  const ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "engine_player_t" &&
      n.namespace_ () == "urn:rpg")
  {
    ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
      ::xsd::cxx::tree::traits< ::RPG_Engine_Player_XMLTree_Type, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "engine_player_t",
    "urn:rpg");
}

::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type >
engine_player_t (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "engine_player_t" &&
      n.namespace_ () == "urn:rpg")
  {
    ::std::auto_ptr< ::RPG_Engine_Player_XMLTree_Type > r (
      ::xsd::cxx::tree::traits< ::RPG_Engine_Player_XMLTree_Type, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "engine_player_t",
    "urn:rpg");
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (const ::std::string& u,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
    ::engine_level_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (const ::std::string& u,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
    ::engine_level_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (const ::std::string& u,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
    ::engine_level_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::std::istream& is,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::engine_level_t (isrc, f, p);
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::std::istream& is,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::engine_level_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::std::istream& is,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::engine_level_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::std::istream& is,
                const ::std::string& sid,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::engine_level_t (isrc, f, p);
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::std::istream& is,
                const ::std::string& sid,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::engine_level_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::std::istream& is,
                const ::std::string& sid,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::engine_level_t (isrc, h, f, p);
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::xercesc::InputSource& i,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
    ::engine_level_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::xercesc::InputSource& i,
                ::xml_schema::error_handler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
    ::engine_level_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::xercesc::InputSource& i,
                ::xercesc::DOMErrorHandler& h,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
    ::engine_level_t (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (const ::xercesc::DOMDocument& d,
                ::xml_schema::flags f,
                const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

    ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
      ::engine_level_t (
        c, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  const ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "engine_level_t" &&
      n.namespace_ () == "urn:rpg")
  {
    ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
      ::xsd::cxx::tree::traits< ::RPG_Engine_Level_XMLTree_Type, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "engine_level_t",
    "urn:rpg");
}

::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type >
engine_level_t (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                ::xml_schema::flags f,
                const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "engine_level_t" &&
      n.namespace_ () == "urn:rpg")
  {
    ::std::auto_ptr< ::RPG_Engine_Level_XMLTree_Type > r (
      ::xsd::cxx::tree::traits< ::RPG_Engine_Level_XMLTree_Type, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "engine_level_t",
    "urn:rpg");
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

void
operator<< (::xercesc::DOMElement& e, const RPG_Engine_Command_XMLTree_Type& i)
{
  e << static_cast< const ::xml_schema::string& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const RPG_Engine_Command_XMLTree_Type& i)
{
  a << static_cast< const ::xml_schema::string& > (i);
}

void
operator<< (::xml_schema::list_stream& l,
            const RPG_Engine_Command_XMLTree_Type& i)
{
  l << static_cast< const ::xml_schema::string& > (i);
}

void
operator<< (::xercesc::DOMElement& e, const RPG_Engine_EntityMode_XMLTree_Type& i)
{
  e << static_cast< const ::xml_schema::string& > (i);
}

void
operator<< (::xercesc::DOMAttr& a, const RPG_Engine_EntityMode_XMLTree_Type& i)
{
  a << static_cast< const ::xml_schema::string& > (i);
}

void
operator<< (::xml_schema::list_stream& l,
            const RPG_Engine_EntityMode_XMLTree_Type& i)
{
  l << static_cast< const ::xml_schema::string& > (i);
}

void
operator<< (::xercesc::DOMElement& e, const RPG_Engine_Player_XMLTree_Type& i)
{
  e << static_cast< const ::RPG_Player_PlayerXML_XMLTree_Type& > (i);

  // position
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "position",
        "urn:rpg",
        e));

    s << i.position ();
  }

  // mode
  //
  for (RPG_Engine_Player_XMLTree_Type::mode_const_iterator
       b (i.mode ().begin ()), n (i.mode ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "mode",
        "urn:rpg",
        e));

    s << *b;
  }

  // sprite
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "sprite",
        "urn:rpg",
        e));

    s << i.sprite ();
  }
}

void
operator<< (::xercesc::DOMElement& e, const RPG_Engine_Level_XMLTree_Type& i)
{
  e << static_cast< const ::xml_schema::type& > (i);

  // name
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "name",
        "urn:rpg",
        e));

    s << i.name ();
  }

  // environment
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "environment",
        "urn:rpg",
        e));

    s << i.environment ();
  }

  // monster
  //
  for (RPG_Engine_Level_XMLTree_Type::monster_const_iterator
       b (i.monster ().begin ()), n (i.monster ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "monster",
        "urn:rpg",
        e));

    s << *b;
  }

  // spawn_interval
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "spawn_interval",
        "urn:rpg",
        e));

    s << i.spawn_interval ();
  }

  // spawn_probability
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "spawn_probability",
        "urn:rpg",
        e));

    s << i.spawn_probability ();
  }

  // max_spawned
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "max_spawned",
        "urn:rpg",
        e));

    s << i.max_spawned ();
  }

  // amble_probability
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "amble_probability",
        "urn:rpg",
        e));

    s << i.amble_probability ();
  }

  // map
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "map",
        "urn:rpg",
        e));

    s << i.map ();
  }

  // door
  //
  for (RPG_Engine_Level_XMLTree_Type::door_const_iterator
       b (i.door ().begin ()), n (i.door ().end ());
       b != n; ++b)
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "door",
        "urn:rpg",
        e));

    s << *b;
  }

  // style
  //
  {
    ::xercesc::DOMElement& s (
      ::xsd::cxx::xml::dom::create_element (
        "style",
        "urn:rpg",
        e));

    s << i.style ();
  }
}

void
engine_player_t (::std::ostream& o,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_player_t (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
engine_player_t (::std::ostream& o,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 ::xml_schema::error_handler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_player_t (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_player_t (::std::ostream& o,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_player_t (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_player_t (::xercesc::XMLFormatTarget& t,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_player_t (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
engine_player_t (::xercesc::XMLFormatTarget& t,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 ::xml_schema::error_handler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_player_t (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_player_t (::xercesc::XMLFormatTarget& t,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_player_t (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_player_t (::xercesc::DOMDocument& d,
                 const ::RPG_Engine_Player_XMLTree_Type& s,
                 ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "engine_player_t" &&
      n.namespace_ () == "urn:rpg")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "engine_player_t",
      "urn:rpg");
  }
}

::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
engine_player_t (const ::RPG_Engine_Player_XMLTree_Type& s,
                 const ::xml_schema::namespace_infomap& m,
                 ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "engine_player_t",
      "urn:rpg",
      m, f));

  ::engine_player_t (*d, s, f);
  return d;
}

void
engine_level_t (::std::ostream& o,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                const ::xml_schema::namespace_infomap& m,
                const ::std::string& e,
                ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_level_t (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
engine_level_t (::std::ostream& o,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                ::xml_schema::error_handler& h,
                const ::xml_schema::namespace_infomap& m,
                const ::std::string& e,
                ::xml_schema::flags f)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_level_t (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_level_t (::std::ostream& o,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                ::xercesc::DOMErrorHandler& h,
                const ::xml_schema::namespace_infomap& m,
                const ::std::string& e,
                ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_level_t (s, m, f));
  ::xsd::cxx::xml::dom::ostream_format_target t (o);
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_level_t (::xercesc::XMLFormatTarget& t,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                const ::xml_schema::namespace_infomap& m,
                const ::std::string& e,
                ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_level_t (s, m, f));

  ::xsd::cxx::tree::error_handler< char > h;

  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
  }
}

void
engine_level_t (::xercesc::XMLFormatTarget& t,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                ::xml_schema::error_handler& h,
                const ::xml_schema::namespace_infomap& m,
                const ::std::string& e,
                ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_level_t (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_level_t (::xercesc::XMLFormatTarget& t,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                ::xercesc::DOMErrorHandler& h,
                const ::xml_schema::namespace_infomap& m,
                const ::std::string& e,
                ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::engine_level_t (s, m, f));
  if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
  {
    throw ::xsd::cxx::tree::serialization< char > ();
  }
}

void
engine_level_t (::xercesc::DOMDocument& d,
                const ::RPG_Engine_Level_XMLTree_Type& s,
                ::xml_schema::flags)
{
  ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "engine_level_t" &&
      n.namespace_ () == "urn:rpg")
  {
    e << s;
  }
  else
  {
    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "engine_level_t",
      "urn:rpg");
  }
}

::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
engine_level_t (const ::RPG_Engine_Level_XMLTree_Type& s,
                const ::xml_schema::namespace_infomap& m,
                ::xml_schema::flags f)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::serialize< char > (
      "engine_level_t",
      "urn:rpg",
      m, f));

  ::engine_level_t (*d, s, f);
  return d;
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

