
// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_CHARACTER_MONSTER_SPECIALABILITYPRECONDITION_H
#define RPG_CHARACTER_MONSTER_SPECIALABILITYPRECONDITION_H

#include "rpg_character_monster_exports.h"

struct RPG_Monster_Export RPG_Character_Monster_SpecialAbilityPreCondition
{
  std::vector<RPG_Common_Condition> targetConditions;
  RPG_Common_Size maxTargetSize;
  RPG_Combat_Check check;
};

#endif
