
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_MONSTER_WEAPONTYPEUNION_H
#define RPG_MONSTER_WEAPONTYPEUNION_H

struct RPG_Monster_WeaponTypeUnion
{
  union
  {
    RPG_Monster_NaturalWeapon naturalweapon;
    RPG_Character_Ability ability;
    RPG_Item_WeaponType weapontype;
    RPG_Combat_SpecialAttack specialattack;
  };

  enum Discriminator_t
  {
    NATURALWEAPON,
    ABILITY,
    WEAPONTYPE,
    SPECIALATTACK,
    INVALID
  };
  Discriminator_t discriminator;
};

#endif
