
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_MONSTER_SPECIALATTACKPROPERTIES_H
#define RPG_MONSTER_SPECIALATTACKPROPERTIES_H

#include "rpg_monster_exports.h"

struct RPG_Monster_Export RPG_Monster_SpecialAttackProperties
 : public RPG_Monster_SpecialBaseProperties
{
  std::vector<RPG_Monster_SpecialAttackPreCondition> preConditions;
  RPG_Monster_AttackAction action;
};

#endif
