
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_MONSTER_SPECIALDEFENSEPROPERTIES_H
#define RPG_MONSTER_SPECIALDEFENSEPROPERTIES_H

struct RPG_Monster_SpecialDefenseProperties
 : public RPG_Monster_SpecialBaseProperties
{
  std::vector<RPG_Monster_DefenseAction> actions;
};

#endif
