
// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_MONSTER_SIZE_H
#define RPG_MONSTER_SIZE_H

struct RPG_Monster_Size
{
  RPG_Common_Size size;
  bool isTall;
};

#endif
