
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_PLAYER_CHARACTERBASEXML_H
#define RPG_PLAYER_CHARACTERBASEXML_H

struct RPG_Player_CharacterBaseXML
{
  std::string name;
  RPG_Player_Abilities abilities;
  RPG_Character_Alignment alignment;
  RPG_Character_Attributes attributes;
  RPG_Common_Size defaultSize;
  RPG_Character_Feats feats;
  RPG_Player_Spells knownSpells;
  ACE_UINT16 maxHP;
  RPG_Character_Skills skills;
};

#endif
