
// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_MAGIC_SPELL_TARGETPROPERTIES_H
#define RPG_MAGIC_SPELL_TARGETPROPERTIES_H

struct RPG_Magic_Spell_TargetProperties
{
  RPG_Common_Amount base;
  unsigned char levelIncrement;
  unsigned char levelIncrementMax;
  RPG_Magic_Spell_AreaOfEffect effect;
  RPG_Common_AreaOfEffect shape;
  unsigned char radius;
  unsigned char height;
  RPG_Magic_Spell_Target target;
  bool rangeIsInHD;
  bool incrementIsReciprocal;
};

#endif
