// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "rpg_magic_XML_parser_base.h"

// RPG_Magic_School_Type_pimpl
//

void RPG_Magic_School_Type_pimpl::
pre ()
{
}

RPG_Magic_School RPG_Magic_School_Type_pimpl::
post_RPG_Magic_School_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Magic_Domain_Type_pimpl
//

void RPG_Magic_Domain_Type_pimpl::
pre ()
{
}

RPG_Magic_Domain RPG_Magic_Domain_Type_pimpl::
post_RPG_Magic_Domain_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Magic_Spell_Type_pimpl
//

void RPG_Magic_Spell_Type_pimpl::
pre ()
{
}

RPG_Magic_Spell RPG_Magic_Spell_Type_pimpl::
post_RPG_Magic_Spell_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Magic_SpecialAbilityClass_Type_pimpl
//

void RPG_Magic_SpecialAbilityClass_Type_pimpl::
pre ()
{
}

RPG_Magic_SpecialAbilityClass RPG_Magic_SpecialAbilityClass_Type_pimpl::
post_RPG_Magic_SpecialAbilityClass_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Magic_SpecialAbility_Type_pimpl
//

void RPG_Magic_SpecialAbility_Type_pimpl::
pre ()
{
}

RPG_Magic_SpecialAbility RPG_Magic_SpecialAbility_Type_pimpl::
post_RPG_Magic_SpecialAbility_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Magic_SpecialAbilityProperties_Type_pimpl
//

void RPG_Magic_SpecialAbilityProperties_Type_pimpl::
pre ()
{
}

void RPG_Magic_SpecialAbilityProperties_Type_pimpl::
abilityClass (const RPG_Magic_SpecialAbilityClass& abilityClass)
{
  // TODO
  //
}

void RPG_Magic_SpecialAbilityProperties_Type_pimpl::
type (const RPG_Magic_SpecialAbility& type)
{
  // TODO
  //
}

void RPG_Magic_SpecialAbilityProperties_Type_pimpl::
amount (const RPG_Dice_Roll& amount)
{
  // TODO
  //
}

void RPG_Magic_SpecialAbilityProperties_Type_pimpl::
alignment (const RPG_Character_Alignment& alignment)
{
  // TODO
  //
}

void RPG_Magic_SpecialAbilityProperties_Type_pimpl::
usage (const RPG_Common_Usage& usage)
{
  // TODO
  //
}

RPG_Magic_SpecialAbilityProperties RPG_Magic_SpecialAbilityProperties_Type_pimpl::
post_RPG_Magic_SpecialAbilityProperties_Type ()
{
  // TODO
  //
  // return ... ;
}

