
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_COMMON_EFFECTDURATION_H
#define RPG_COMMON_EFFECTDURATION_H

#include "rpg_common_exports.h"

struct RPG_Common_Export RPG_Common_EffectDuration
{
  RPG_Common_Amount base;
  ACE_INT8 levelIncrement;
  ACE_UINT8 levelIncrementMax;
  ACE_UINT8 reciprocalIncrement;
  bool isMaxDelay;
  bool incrementIsInHD;
};

#endif
