// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef CXX_____RPG_COMMON_ENVIRONMENT_XML_TYPES_H
#define CXX_____RPG_COMMON_ENVIRONMENT_XML_TYPES_H

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4009911L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

// Forward declarations
//
class RPG_Common_Plane_Type_pskel;
class RPG_Common_Terrain_Type_pskel;
class RPG_Common_Track_Type_pskel;
class RPG_Common_Climate_Type_pskel;
class RPG_Common_TimeOfDay_Type_pskel;
class RPG_Common_AmbientLighting_Type_pskel;
class RPG_Common_Environment_Type_pskel;

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_PARSER_USE_CHAR
#define XSD_CXX_PARSER_USE_CHAR
#endif

#include "rpg_XMLSchema_XML_types.h"

#include "rpg_common_environment_incl.h"

class RPG_Common_Plane_Type_pskel: public virtual ::xml_schema::string_pskel
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual RPG_Common_Plane
  post_RPG_Common_Plane_Type () = 0;
};

class RPG_Common_Terrain_Type_pskel: public virtual ::xml_schema::string_pskel
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual RPG_Common_Terrain
  post_RPG_Common_Terrain_Type () = 0;
};

class RPG_Common_Track_Type_pskel: public virtual ::xml_schema::string_pskel
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual RPG_Common_Track
  post_RPG_Common_Track_Type () = 0;
};

class RPG_Common_Climate_Type_pskel: public virtual ::xml_schema::string_pskel
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual RPG_Common_Climate
  post_RPG_Common_Climate_Type () = 0;
};

class RPG_Common_TimeOfDay_Type_pskel: public virtual ::xml_schema::string_pskel
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual RPG_Common_TimeOfDay
  post_RPG_Common_TimeOfDay_Type () = 0;
};

class RPG_Common_AmbientLighting_Type_pskel: public virtual ::xml_schema::string_pskel
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual RPG_Common_AmbientLighting
  post_RPG_Common_AmbientLighting_Type () = 0;
};

class RPG_Common_Environment_Type_pskel: public ::xml_schema::complex_content
{
  public:
  // Parser callbacks. Override them in your implementation.
  //
  // virtual void
  // pre ();

  virtual void
  plane (const RPG_Common_Plane&);

  virtual void
  terrain (const RPG_Common_Terrain&);

  virtual void
  climate (const RPG_Common_Climate&);

  virtual void
  time (const RPG_Common_TimeOfDay&);

  virtual void
  lighting (const RPG_Common_AmbientLighting&);

  virtual void
  outdoors (bool);

  virtual RPG_Common_Environment
  post_RPG_Common_Environment_Type () = 0;

  // Parser construction API.
  //
  void
  plane_parser (::RPG_Common_Plane_Type_pskel&);

  void
  terrain_parser (::RPG_Common_Terrain_Type_pskel&);

  void
  climate_parser (::RPG_Common_Climate_Type_pskel&);

  void
  time_parser (::RPG_Common_TimeOfDay_Type_pskel&);

  void
  lighting_parser (::RPG_Common_AmbientLighting_Type_pskel&);

  void
  outdoors_parser (::xml_schema::boolean_pskel&);

  void
  parsers (::RPG_Common_Plane_Type_pskel& /* plane */,
           ::RPG_Common_Terrain_Type_pskel& /* terrain */,
           ::RPG_Common_Climate_Type_pskel& /* climate */,
           ::RPG_Common_TimeOfDay_Type_pskel& /* time */,
           ::RPG_Common_AmbientLighting_Type_pskel& /* lighting */,
           ::xml_schema::boolean_pskel& /* outdoors */);

  // Constructor.
  //
  RPG_Common_Environment_Type_pskel ();

  // Implementation.
  //
  protected:
  virtual bool
  _start_element_impl (const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string&,
                       const ::xml_schema::ro_string*);

  virtual bool
  _end_element_impl (const ::xml_schema::ro_string&,
                     const ::xml_schema::ro_string&);

  protected:
  ::RPG_Common_Plane_Type_pskel* plane_parser_;
  ::RPG_Common_Terrain_Type_pskel* terrain_parser_;
  ::RPG_Common_Climate_Type_pskel* climate_parser_;
  ::RPG_Common_TimeOfDay_Type_pskel* time_parser_;
  ::RPG_Common_AmbientLighting_Type_pskel* lighting_parser_;
  ::xml_schema::boolean_pskel* outdoors_parser_;
};

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // CXX_____RPG_COMMON_ENVIRONMENT_XML_TYPES_H
