// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "rpg_common_XML_parser_base.h"

// RPG_Common_Attribute_Type_pimpl
//

void RPG_Common_Attribute_Type_pimpl::
pre ()
{
}

RPG_Common_Attribute RPG_Common_Attribute_Type_pimpl::
post_RPG_Common_Attribute_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Common_PhysicalDamageType_Type_pimpl
//

void RPG_Common_PhysicalDamageType_Type_pimpl::
pre ()
{
}

RPG_Common_PhysicalDamageType RPG_Common_PhysicalDamageType_Type_pimpl::
post_RPG_Common_PhysicalDamageType_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Common_CheckType_Type_pimpl
//

void RPG_Common_CheckType_Type_pimpl::
pre ()
{
}

RPG_Common_CheckType RPG_Common_CheckType_Type_pimpl::
post_RPG_Common_CheckType_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Common_SavingThrow_Type_pimpl
//

void RPG_Common_SavingThrow_Type_pimpl::
pre ()
{
}

RPG_Common_SavingThrow RPG_Common_SavingThrow_Type_pimpl::
post_RPG_Common_SavingThrow_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Common_BaseCheckTypeUnion_Type_pimpl
//

void RPG_Common_BaseCheckTypeUnion_Type_pimpl::
pre ()
{
}

void RPG_Common_BaseCheckTypeUnion_Type_pimpl::
_characters (const ::xml_schema::ro_string& s)
{
  // TODO
  //
}

RPG_Common_BaseCheckTypeUnion RPG_Common_BaseCheckTypeUnion_Type_pimpl::
post_RPG_Common_BaseCheckTypeUnion_Type ()
{
  // TODO
  //
  // return ... ;
}

// RPG_Common_SaveReductionType_Type_pimpl
//

void RPG_Common_SaveReductionType_Type_pimpl::
pre ()
{
}

RPG_Common_SaveReductionType RPG_Common_SaveReductionType_Type_pimpl::
post_RPG_Common_SaveReductionType_Type ()
{
  const ::std::string& v (post_string ());

  // TODO
  //
  // return ... ;
}

// RPG_Common_SavingThrowCheck_Type_pimpl
//

void RPG_Common_SavingThrowCheck_Type_pimpl::
pre ()
{
}

void RPG_Common_SavingThrowCheck_Type_pimpl::
type (const RPG_Common_SavingThrow& type)
{
  // TODO
  //
}

void RPG_Common_SavingThrowCheck_Type_pimpl::
attribute (const RPG_Common_Attribute& attribute)
{
  // TODO
  //
}

void RPG_Common_SavingThrowCheck_Type_pimpl::
difficultyClass (unsigned char difficultyClass)
{
  // TODO
  //
}

void RPG_Common_SavingThrowCheck_Type_pimpl::
reduction (const RPG_Common_SaveReductionType& reduction)
{
  // TODO
  //
}

RPG_Common_SavingThrowCheck RPG_Common_SavingThrowCheck_Type_pimpl::
post_RPG_Common_SavingThrowCheck_Type ()
{
  // TODO
  //
  // return ... ;
}

// RPG_Common_Usage_Type_pimpl
//

void RPG_Common_Usage_Type_pimpl::
pre ()
{
}

void RPG_Common_Usage_Type_pimpl::
numUses (unsigned char numUses)
{
  // TODO
  //
}

void RPG_Common_Usage_Type_pimpl::
period (unsigned int period)
{
  // TODO
  //
}

RPG_Common_Usage RPG_Common_Usage_Type_pimpl::
post_RPG_Common_Usage_Type ()
{
  // TODO
  //
  // return ... ;
}

// RPG_Common_Duration_Type_pimpl
//

void RPG_Common_Duration_Type_pimpl::
pre ()
{
}

void RPG_Common_Duration_Type_pimpl::
activationPeriod (unsigned short activationPeriod)
{
  // TODO
  //
}

void RPG_Common_Duration_Type_pimpl::
interval (unsigned short interval)
{
  // TODO
  //
}

void RPG_Common_Duration_Type_pimpl::
totalDuration (unsigned short totalDuration)
{
  // TODO
  //
}

RPG_Common_Duration RPG_Common_Duration_Type_pimpl::
post_RPG_Common_Duration_Type ()
{
  // TODO
  //
  // return ... ;
}

