
// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_COMMON_ENVIRONMENT_H
#define RPG_COMMON_ENVIRONMENT_H

#include "rpg_common_exports.h"

struct RPG_Common_Export RPG_Common_Environment
{
  RPG_Common_Terrain terrain;
  RPG_Common_Climate climate;
  RPG_Common_TimeOfDay time;
  bool outdoors;
};

#endif
