
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_COMMON_USAGE_H
#define RPG_COMMON_USAGE_H

#include "rpg_common_exports.h"

struct RPG_Common_Export RPG_Common_Usage
{
  ACE_UINT8 numUses;
  ACE_UINT32 period;
  RPG_Dice_Roll interval;
};

#endif
