
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_COMMON_SAVINGTHROWCHECK_H
#define RPG_COMMON_SAVINGTHROWCHECK_H

struct RPG_Common_SavingThrowCheck
{
  RPG_Common_SavingThrow type;
  RPG_Common_Attribute attribute;
  ACE_UINT8 difficultyClass;
  RPG_Common_SaveReductionType reduction;
};

#endif
