
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_COMMON_SAVINGTHROWCHECK_H
#define RPG_COMMON_SAVINGTHROWCHECK_H

struct RPG_Common_SavingThrowCheck
{
  RPG_Common_SavingThrow type;
  RPG_Common_Attribute attribute;
  unsigned char difficultyClass;
  RPG_Common_SaveReductionType reduction;
};

#endif
