
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_CHARACTER_ALIGNMENT_H
#define RPG_CHARACTER_ALIGNMENT_H

struct RPG_Character_Alignment
{
  RPG_Character_AlignmentCivic civic;
  RPG_Character_AlignmentEthic ethic;
};

#endif
