
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_CHARACTER_FEATS_H
#define RPG_CHARACTER_FEATS_H

#include "rpg_character_exports.h"

struct RPG_Character_Export RPG_Character_Feats
{
  std::vector<RPG_Character_Feat> feats;
};

#endif
