
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.0.1-devel
// -------------------------------- * * * ----------------------------------- //

#ifndef RPG_CHARACTER_ATTRIBUTES_H
#define RPG_CHARACTER_ATTRIBUTES_H

struct RPG_Character_Attributes
{
  ACE_UINT8 strength;
  ACE_UINT8 dexterity;
  ACE_UINT8 constitution;
  ACE_UINT8 intelligence;
  ACE_UINT8 wisdom;
  ACE_UINT8 charisma;
};

#endif
