/***************************************************************************
 *   Copyright (C) 2009 by Erik Sohns   *
 *   erik.sohns@web.de   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
#ifndef RPG_CHARACTER_SKILLS_COMMON_H
#define RPG_CHARACTER_SKILLS_COMMON_H

#include <map>
// #include <vector>

enum RPG_Character_Skill
{
  SKILL_APPRAISE = 0,
  SKILL_BALANCE,
  SKILL_BLUFF,
  SKILL_CLIMB,
  SKILL_CONCENTRATION,
  SKILL_CRAFT,
  SKILL_DECIPHER_SCRIPT,
  SKILL_DIPLOMACY,
  SKILL_DISABLE_DEVICE,
  SKILL_DISGUISE,
  SKILL_ESCAPE_ARTIST,
  SKILL_FORGERY,
  SKILL_GATHER_INFORMATION,
  SKILL_HANDLE_ANIMAL,
  SKILL_HEAL,
  SKILL_HIDE,
  SKILL_INTIMIDATE,
  SKILL_JUMP,
  SKILL_KNOWLEDGE,
  SKILL_LISTEN,
  SKILL_MOVE_SILENTLY,
  SKILL_OPEN_LOCK,
  SKILL_PERFORM,
  SKILL_PROFESSION,
  SKILL_RIDE,
  SKILL_SEARCH,
  SKILL_SENSE_MOTIVE,
  SKILL_SLEIGHT_OF_HAND,
  SKILL_SPEAK_LANGUAGE,
  SKILL_SPELLCRAFT,
  SKILL_SPOT,
  SKILL_SURVIVAL,
  SKILL_SWIM,
  SKILL_TUMBLE,
  SKILL_USE_MAGIC_DEVICE,
  SKILL_USE_ROPE,
  //
  SKILL_MAX,
  SKILL_INVALID
};

enum RPG_Character_Feat
{
  // fighter bonus
  FEAT_BLIND_FIGHT = 0,
  FEAT_COMBAT_EXPERTISE,
  FEAT_IMPROVED_DISARM,
  FEAT_IMPROVED_FEINT,
  FEAT_IMPROVED_TRIP,
  FEAT_WHIRLWIND_ATTACK,
  FEAT_COMBAT_REFLEXES,
  FEAT_DODGE,
  FEAT_MOBILITY,
  FEAT_SPRING_ATTACK,
  FEAT_PROFICIENCY_EXOTIC_WEAPONS,
  FEAT_IMPROVED_CRITICAL,
  FEAT_IMPROVED_INITIATIVE,
  FEAT_IMPROVED_SHIELD_BASH,
  FEAT_IMPROVED_UNARMED_STRIKE,
  FEAT_DEFLECT_ARROWS,
  FEAT_IMPROVED_GRAPPLE,
  FEAT_SNATCH_ARROWS,
  FEAT_STUNNING_FIST,
  FEAT_MOUNTED_COMBAT,
  FEAT_MOUNTED_ARCHERY,
  FEAT_RIDE_BY_ATTACK,
  FEAT_SPIRITED_CHARGE,
  FEAT_TRAMPLE,
  FEAT_POINT_BLANK_SHOT,
  FEAT_FAR_SHOT,
  FEAT_PRECISE_SHOT,
  FEAT_RAPID_SHOT,
  FEAT_MANY_SHOT,
  FEAT_SHOT_ON_THE_RUN,
  FEAT_IMPROVED_PRECISE_SHOT,
  FEAT_POWER_ATTACK,
  FEAT_CLEAVE,
  FEAT_GREAT_CLEAVE,
  FEAT_IMPROVED_BULL_RUSH,
  FEAT_IMPROVED_OVERRUN,
  FEAT_IMPROVED_SUNDER,
  FEAT_QUICK_DRAW,
  FEAT_RAPID_RELOAD,
  FEAT_TWO_WEAPON_FIGHTING,
  FEAT_TWO_WEAPON_DEFENSE,
  FEAT_IMPROVED_TWO_WEAPON_FIGHTING,
  FEAT_GREATER_TWO_WEAPON_FIGHTING,
  FEAT_WEAPON_FINESSE,
  FEAT_WEAPON_FOCUS,
  FEAT_WEAPON_SPECIALIZATION,
  FEAT_GREATER_WEAPON_FOCUS,
  FEAT_GREATER_WEAPON_SPECIALIZATION,
  // item creation
  FEAT_BREW_POTION,
  FEAT_CRAFT_MAGIC_ARMS_AND_ARMOR,
  FEAT_CRAFT_ROD,
  FEAT_CRAFT_STAFF,
  FEAT_CRAFT_WAND,
  FEAT_CRAFT_WONDROUS_ITEM,
  FEAT_FORGE_RING,
  FEAT_SCRIBE_SCROLL,
  // meta-magic
  FEAT_EMPOWER_SPELL,
  FEAT_ENLARGE_SPELL,
  FEAT_EXTEND_SPELL,
  FEAT_HEIGHTEN_SPELL,
  FEAT_MAXIMIZE_SPELL,
  FEAT_QUICKEN_SPELL,
  FEAT_SILENT_SPELL,
  FEAT_WIDEN_SPELL,
  // general
  FEAT_ACROBATIC,
  FEAT_AGILE,
  FEAT_ALERTNESS,
  FEAT_ANIMAL_AFFINITY,
  FEAT_ARMOR_PROFICIENCY_LIGHT,
  FEAT_ARMOR_PROFICIENCY_MEDIUM,
  FEAT_ARMOR_PROFICIENCY_HEAVY,
  FEAT_ATHLETIC,
  FEAT_AUGMENT_SUMMONING,
  FEAT_COMBAT_CASTING,
  FEAT_DECEITFUL,
  FEAT_DEFT_HANDS,
  FEAT_DILIGENT,
  FEAT_ENDURANCE,
  FEAT_DIE_HARD,
  FEAT_ESCHEW_MATERIALS,
  FEAT_EXTRA_TURNING,
  FEAT_GREAT_FORTITUDE,
  FEAT_IMPROVED_COUNTERSPELL,
  FEAT_IMPROVED_FAMILIAR,
  FEAT_IMPROVED_TURNING,
  FEAT_INVESTIGATOR,
  FEAT_IRON_WILL,
  FEAT_LEADERSHIP,
  FEAT_LIGHTNING_REFLEXES,
  FEAT_MAGICAL_APTITUDE,
  FEAT_PROFICIENCY_MARTIAL_WEAPONS,
  FEAT_NATURAL_SPELL,
  FEAT_NEGOTIATOR,
  FEAT_NIMBLE_FINGERS,
  FEAT_PERSUASIVE,
  FEAT_RUN,
  FEAT_SELF_SUFFICIENT,
  FEAT_PROFICIENCY_SHIELD,
  FEAT_PROFICIENCY_SIMPLE_WEAPONS,
  FEAT_SKILL_FOCUS,
  FEAT_SPELL_FOCUS,
  FEAT_GREATER_SPELL_FOCUS,
  FEAT_SPELL_MASTERY,
  FEAT_SPELL_PENETRATION,
  FEAT_GREATER_SPELL_PENETRATION,
  FEAT_STEALTHY,
  FEAT_TOUGHNESS,
  FEAT_TRACK,
  //
  FEAT_MAX,
  FEAT_INVALID
};

// some useful types
typedef std::map<RPG_Character_Skill, unsigned char> RPG_CHARACTER_SKILLS_T;
typedef RPG_CHARACTER_SKILLS_T::const_iterator RPG_CHARACTER_SKILLSITERATOR_T;
// typedef std::vector<RPG_Character_Skill> RPG_CHARACTER_SKILLSLIST_T;
// typedef RPG_CHARACTER_SKILLSLIST_T::const_iterator RPG_CHARACTER_SKILLSLISTITERATOR_T;

#endif
