
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_CHARACTER_SKILLS_H
#define RPG_CHARACTER_SKILLS_H

struct RPG_Character_Skills
{
  std::vector<RPG_Character_SkillValue> skills;
};

#endif
