# project
set (PROJECT_NAME yarp)
if (UNIX)
 set (PROJECT_LIBNAME lib${PROJECT_NAME})
elseif (WIN32)
 set (PROJECT_LIBNAME ${PROJECT_NAME})
endif ()

# version
set (VERSION_MAJOR 0)
set (VERSION_MINOR 0)
set (VERSION_MICRO 1)
set (VERSION_DEVEL devel)
set (VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_MICRO})
if (VERSION_DEVEL)
 set (VERSION_FULL ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_MICRO}-${VERSION_DEVEL})
else ()
 set (VERSION_FULL ${VERSION})
endif ()

# config.h
set (PACKAGE ${PROJECT_LIBNAME})
set (${PROJECT_NAME}_PACKAGE ${PACKAGE})

set (PACKAGE_BUGREPORT "erik.sohns@posteo.de")
set (${PROJECT_NAME}_PACKAGE_BUGREPORT ${PACKAGE_BUGREPORT})

set (PACKAGE_NAME ${PROJECT_NAME})
set (${PROJECT_NAME}_PACKAGE_NAME ${PACKAGE_NAME})

set (PACKAGE_STRING "${PROJECT_NAME} ${VERSION_FULL}")
set (${PROJECT_NAME}_PACKAGE_STRING ${PACKAGE_STRING})

set (PACKAGE_TARNAME "${PROJECT_LIBNAME}-${VERSION_FULL}.tar.gz")
set (${PROJECT_NAME}_PACKAGE_TARNAME ${PACKAGE_TARNAME})

set (PACKAGE_URL "https://github.com/esohns/${PROJECT_NAME}")
set (${PROJECT_NAME}_PACKAGE_URL ${PACKAGE_URL})

set (PACKAGE_VERSION ${VERSION})
set (${PROJECT_NAME}_PACKAGE_VERSION ${PACKAGE_VERSION})
set (PACKAGE_VERSION_FULL ${VERSION_FULL})
set (${PROJECT_NAME}_PACKAGE_VERSION_FULL ${PACKAGE_VERSION_FULL})

set (${PROJECT_NAME}_VERSION_MAJOR ${VERSION_MAJOR})
set (${PROJECT_NAME}_VERSION_MINOR ${VERSION_MINOR})
set (${PROJECT_NAME}_VERSION_MICRO ${VERSION_MICRO})
set (${PROJECT_NAME}_VERSION_DEVEL ${VERSION_DEVEL})

set (PACKAGE_DESCRIPTION "yarp is a framework for creating RPGs")
set (${PROJECT_NAME}_PACKAGE_DESCRIPTION ${PACKAGE_DESCRIPTION})
set (PACKAGE_DESCRIPTION_SUMMARY "yarp is a framework for creating RPGs")
set (${PROJECT_NAME}_PACKAGE_DESCRIPTION_SUMMARY ${PACKAGE_DESCRIPTION_SUMMARY})

# cpack
# Package section (see http://packages.debian.org/stable/)
set (PACKAGE_SECTION "devel") # Debian
#set (PACKAGE_SECTION "Development/Libraries")
