find_package (XercesC)
if (XERCESC_FOUND)
 message (STATUS "Found xerces-c")
else ()
# message (WARNING "could not find xerces-c, continuing")
endif (XERCESC_FOUND)

if (UNIX)
 if (NOT XERCESC_FOUND)
  pkg_check_modules (PKG_XERCESC xerces-c)
  if (PKG_XERCESC_FOUND)
   message (STATUS "Found xerces-c")
   add_definitions (-DXERCES_C_SUPPORT)
  else ()
   set (XERCESC_LIB_FILE libxerces-c.a)
   find_library (XERCESC_LIBRARY ${XERCESC_LIB_FILE}
                 HINTS /usr/lib64 /usr/lib
                 PATH_SUFFIXES x86_64-linux-gnu
                 DOC "searching for ${XERCESC_LIB_FILE} (system paths)")
   if (XERCESC_LIBRARY)
    message (STATUS "Found xerces-c library \"${XERCESC_LIBRARY}\"")
    add_definitions (-DXERCESC_SUPPORT)
   else ()
    message (FATAL_ERROR "could not find ${XERCESC_LIB_FILE}, aborting")
   endif (XERCESC_LIBRARY)
  endif (PKG_XERCESC_FOUND)
 endif (NOT XERCESC_FOUND)
elseif (WIN32)
 if (NOT XERCESC_FOUND)
  set (XERCESC_INCLUDE_DIR "$ENV{LIB_ROOT}/xerces-c/include")
  set (XERCESC_LIB "xerces-c.dll.lib")
  find_library (XERCESC_LIBRARY
                NAMES ${XERCESC_LIB}
                PATHS "$ENV{LIB_ROOT}/xerces-c/lib"
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                NO_DEFAULT_PATH)
  if (XERCESC_INCLUDE_DIR AND XERCESC_LIBRARY)
    message (STATUS "found xerces-c")
    set (XERCESC_FOUND TRUE)
    set (XERCESC_INCLUDE_DIRS "${XERCESC_INCLUDE_DIR}")
    set (XERCESC_LIBRARIES "${XERCESC_LIBRARY}")
    set (XERCESC_LIB_DIR "$ENV{LIB_ROOT}/xerces-c/bin/${CMAKE_BUILD_TYPE}")
    file (TO_NATIVE_PATH "${XERCESC_LIB_DIR}" XERCESC_LIB_DIR)
    string (REPLACE "\\" "\\\\" XERCESC_LIB_DIR ${XERCESC_LIB_DIR})
  else ()
    message (WARNING "could not find xerces-c, continuing")
  endif (XERCESC_INCLUDE_DIR AND XERCESC_LIBRARY)
 endif (NOT XERCESC_FOUND)
endif ()
if (XERCESC_FOUND)
 option (XERCESC_SUPPORT "enable xerces-c support" ON)
 if (XERCESC_SUPPORT)
  add_definitions (-DXERCESC_SUPPORT)
  add_compile_definitions (LIBXERCES_C_SHARED)
 endif (XERCESC_SUPPORT)
endif (XERCESC_FOUND)
