
// -------------------------------- * * * ----------------------------------- //
// PLEASE NOTE: this file was/is generated by // -------------------------------- * * * ----------------------------------- //

#pragma once
#ifndef RPG_ITEM_WEAPONCATEGORY_H
#define RPG_ITEM_WEAPONCATEGORY_H

enum RPG_Item_WeaponCategory
{
  WEAPONCATEGORY_SIMPLE = 0,
  WEAPONCATEGORY_MARTIAL,
  WEAPONCATEGORY_EXOTIC,
  //
  RPG_ITEM_WEAPONCATEGORY_MAX,
  RPG_ITEM_WEAPONCATEGORY_INVALID
};

#include "ace/Global_Macros.h"

#include <map>
#include <string>

typedef std::map<RPG_Item_WeaponCategory, std::string> RPG_Item_WeaponCategoryToStringTable_t;
typedef RPG_Item_WeaponCategoryToStringTable_t::const_iterator RPG_Item_WeaponCategoryToStringTableIterator_t;

class RPG_Item_WeaponCategoryHelper
{
 public:
  inline static void init()
  {
    myRPG_Item_WeaponCategoryToStringTable.clear();
    myRPG_Item_WeaponCategoryToStringTable.insert(std::make_pair(WEAPONCATEGORY_SIMPLE, ACE_TEXT_ALWAYS_CHAR("WEAPONCATEGORY_SIMPLE")));
    myRPG_Item_WeaponCategoryToStringTable.insert(std::make_pair(WEAPONCATEGORY_MARTIAL, ACE_TEXT_ALWAYS_CHAR("WEAPONCATEGORY_MARTIAL")));
    myRPG_Item_WeaponCategoryToStringTable.insert(std::make_pair(WEAPONCATEGORY_EXOTIC, ACE_TEXT_ALWAYS_CHAR("WEAPONCATEGORY_EXOTIC")));
  };

  inline static std::string RPG_Item_WeaponCategoryToString(const RPG_Item_WeaponCategory& element_in)
  {
    std::string result;
    RPG_Item_WeaponCategoryToStringTableIterator_t iterator = myRPG_Item_WeaponCategoryToStringTable.find(element_in);
    if (iterator != myRPG_Item_WeaponCategoryToStringTable.end())
      result = iterator->second;
    else
      result = ACE_TEXT_ALWAYS_CHAR("RPG_ITEM_WEAPONCATEGORY_INVALID");

    return result;
  };

  inline static RPG_Item_WeaponCategory stringToRPG_Item_WeaponCategory(const std::string& string_in)
  {
    RPG_Item_WeaponCategoryToStringTableIterator_t iterator = myRPG_Item_WeaponCategoryToStringTable.begin();
    do
    {
      if (iterator->second == string_in)
        return iterator->first;

      iterator++;
    } while (iterator != myRPG_Item_WeaponCategoryToStringTable.end());

    return RPG_ITEM_WEAPONCATEGORY_INVALID;
  };

  static RPG_Item_WeaponCategoryToStringTable_t myRPG_Item_WeaponCategoryToStringTable;

 private:
  ACE_UNIMPLEMENTED_FUNC(RPG_Item_WeaponCategoryHelper());
  ACE_UNIMPLEMENTED_FUNC(RPG_Item_WeaponCategoryHelper(const RPG_Item_WeaponCategoryHelper&));
  ACE_UNIMPLEMENTED_FUNC(RPG_Item_WeaponCategoryHelper& operator=(const RPG_Item_WeaponCategoryHelper&));
};

#endif
