
// -------------------------------- * * * -------------------------------- //
// PLEASE NOTE: this file was/is generated by XML2CppCode 0.1
// -------------------------------- * * * -------------------------------- //

#pragma once
#ifndef RPG_ITEM_ARMORPROPERTIESBASE_H
#define RPG_ITEM_ARMORPROPERTIESBASE_H

struct RPG_Item_ArmorPropertiesBase
 : public RPG_Item_PropertiesBase
{
  RPG_Item_ArmorType armorType;
  RPG_Item_ArmorCategory armorCategory;
  unsigned char baseArmorBonus;
  unsigned char maxDexterityBonus;
  char armorCheckPenalty;
  unsigned char arcaneSpellFailure;
  unsigned short int baseSpeed;
};

#endif
